spring.application.name=e-ticket-booking-system

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Timezone
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh


#CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh-token-expiration=${JWT_REFRESH_EXPIRATION}

# Booking Configuration
booking.hold-duration-minutes=${BOOKING_HOLD_DURATION}

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PayOS Configuration
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Frontend URL for OAuth2 redirect
app.frontend-url=${FRONTEND_URL}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}
payos.return-url=${PAYOS_RETURN_URL}
payos.cancel-url=${PAYOS_CANCEL_URL}


# Cookie secure flag for SameSite=None handling in dev (set true in prod with HTTPS)
app.cookie-secure=true


#Cookie SameSite configuration
app.cookie-samesite=${COOKIE_SAMESITE:None}


#Nginx Configuration
server.forward-headers-strategy=framework
spring.profiles.active=prod

