export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  ORGANIZER: 'ORGANIZER',
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
};

export const EVENT_STATUS = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
};

export const PAYMENT_METHODS = ['PAYOS'];

export const TRANSACTION_TYPES = {
  PAYMENT: 'PAYMENT',
  REFUND: 'REFUND',
  EXCHANGE_PAYMENT: 'EXCHANGE_PAYMENT',
};

export const WALLET_TRANSACTION_TYPES = {
  REVENUE: 'REVENUE',
  WITHDRAWAL: 'WITHDRAWAL',
  REFUND_DEDUCTION: 'REFUND_DEDUCTION',
};

export const SCHEDULE_STATUS = {
  SCHEDULED: 'SCHEDULED',
  ONGOING: 'ONGOING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

export const DISCOUNT_TYPES = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED_AMOUNT: 'FIXED_AMOUNT',
};

export const APPLICATION_TYPES = {
  GLOBAL: 'GLOBAL',
  ORGANIZER_ALL: 'ORGANIZER_ALL',
  SPECIFIC_EVENTS: 'SPECIFIC_EVENTS',
};

export const EXCHANGE_TYPES = {
  SELL: 'SELL',
  TRADE: 'TRADE',
  BOTH: 'BOTH',
};

export const SEAT_TYPES = {
  VIP: 'VIP',
  REGULAR: 'REGULAR',
  WHEELCHAIR: 'WHEELCHAIR',
};
